apiVersion: v1
kind: Service
metadata:
  name: ms-pacman-core
  namespace: nerdearla
spec:
  selector:
    app: ms-pacman-core
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
