apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: nerdearla
spec:
  selector:
    app: postgres-db
  type: NodePort
  ports:
    - name: http
      port: 5432
      targetPort: 5432